// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrMfn4f9IqgEoz8YIwD-F7RlVChPKlWo',
    appId: '1:218156546523:web:c97b4beb3497988374cffe',
    messagingSenderId: '218156546523',
    projectId: 'userlist-764a8',
    authDomain: 'userlist-764a8.firebaseapp.com',
    storageBucket: 'userlist-764a8.firebasestorage.app',
    measurementId: 'G-DG20YE855C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCxJl8-0EvrIaoWc64PIW4H-O6_JB2YKI',
    appId: '1:218156546523:android:bdfaaf9ee1b411bd74cffe',
    messagingSenderId: '218156546523',
    projectId: 'userlist-764a8',
    storageBucket: 'userlist-764a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgR9_w7jGLRQRGLwc5wzI5Ll4wGSbEghU',
    appId: '1:218156546523:ios:4da3cc96303aabdd74cffe',
    messagingSenderId: '218156546523',
    projectId: 'userlist-764a8',
    storageBucket: 'userlist-764a8.firebasestorage.app',
    iosBundleId: 'com.example.brototypeuserlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgR9_w7jGLRQRGLwc5wzI5Ll4wGSbEghU',
    appId: '1:218156546523:ios:4da3cc96303aabdd74cffe',
    messagingSenderId: '218156546523',
    projectId: 'userlist-764a8',
    storageBucket: 'userlist-764a8.firebasestorage.app',
    iosBundleId: 'com.example.brototypeuserlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZrMfn4f9IqgEoz8YIwD-F7RlVChPKlWo',
    appId: '1:218156546523:web:11515d8aff23af5274cffe',
    messagingSenderId: '218156546523',
    projectId: 'userlist-764a8',
    authDomain: 'userlist-764a8.firebaseapp.com',
    storageBucket: 'userlist-764a8.firebasestorage.app',
    measurementId: 'G-48RGXBXLCC',
  );
}
